### ISSUE TITLE
Release of the logo

### ISSUE THREAD

**Issue by bryan-brancotte** [edamontology/edamontology#666]
Hi,

Once a logo has been selected, where will it be released ? 

I propose that it is shared in https://github.com/edamontology/edamontology next to `EDAMrelations.png`, named `EDAM.svg`

**Comment by bryan-brancotte** [comment]
Hi @matuskalas, 

I agree with you, we should first set up the old logo, and later update it.

Where can the logo be found ? I can only find it at https://avatars.githubusercontent.com/u/7922809?s=200&v=4

**Comment by Babsbarokah** [comment]
Hello

This gives me a clearer view of some of the end goal of the logo.

If I get you right, @matuskalas a PR should be made to add the old logo to the repo https://github.com/edamontology/edamontology.org?

I'd like to take it up

**Comment by matuskalas** [comment]
Awesome, thank you @Babsbarokah! Please take the http://edamontology.org/favicon.ico and add it there as `favicon.ico`. 🙏🏽

**Comment by Babsbarokah** [comment]
Done

**Comment by bryan-brancotte** [comment]
Hi @matuskalas @Babsbarokah, I already proposed the old logo with #672 yesterday, I should have mentioned it here. The rectangle logo and the favicon are still missing although.

**Comment by matuskalas** [comment]
@Babsbarokah includes the favicon to the edamontology.org repo, so that complements your PR to this repo @bryan-brancotte 👍🏽
(@Babsbarokah I added a comment to your commit in your fork)

**Comment by Babsbarokah** [comment]
Seen, thanks.
